config/routes.rb
Rails.application.routes.draw do
  # Deviseのルーティングを設定
  devise_for :users
    
  devise_scope :user do
    root "devise/sessions#new"
  end

  resources :tasks
  resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  # ユーザー編集ページへのルーティングを追加
  # get 'users/:id/edit', to: 'users#edit', as: 'edit_user_profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user

    def self.user_id_from_name(username)
        user = User.find_by(name: username)
        user&.id
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :tasks
  validates :name, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    user_path(resource) # ログイン後にリダイレクトするパスを指定してください
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: %i[edit update destroy]
    # Task 一覧画面表示
    def index
        @tasks = Task.all
    end
    # Task 作成画面
    def new
        @task = Task.new
    end
    # Task 作成処理
    def create
        @task = Task.new(task_params)
        @task.user_id = Task.user_id_from_name(params[:task][:user_name]) # ユーザー名からユーザーIDを検索
        if @task.save
          redirect_to tasks_path
        else
            render :new
        end
      end
    # Task 編集画面表示
    def edit
    end
    # Task 更新処理
    def update
        if @task.update(task_params)
          redirect_to tasks_path
        end
    end
#    def update
#        @task.update(task_params)
#    end
    # Task 削除処理
    def destroy
        @task.destroy
        redirect_to tasks_path
    end
    # id指定でtaskを検索して設定
    def set_task
        @task = Task.find(params[:id])
    end

    private
    # ストロングパラメータ
    # permitで指定した項目を許可する
    def task_params
        params.require(:task).permit(:user_id, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :show

  # user 一覧画面表示
  def index
    @users = User.all
  end

  # user 画面表示
  def show
    @user = User.find(params[:id])
    if user_signed_in? && @user == current_user
      # この部分は何も処理しない
    else
      # ログインしていないか、他のユーザーの詳細ページにアクセスしようとした場合はリダイレクト
      redirect_to users_path, alert: "他のユーザーの詳細ページにアクセスする権限がありません"
    end
  end
  
  def edit
    # 現在のユーザー情報を取得して、form_forに渡す
    @user = current_user
  end

  # user 作成画面表示
  def new
    @user = User.new
  end

  # user 作成処理
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to action: :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %> - ToDoアプリ</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <div><%= form.label :content %></div>
  <div><%= form.text_area :content %></div>
  <div><%= form.submit %></div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>
<div><%= link_to "Back to tasks", tasks_path %></div>
<div><%= link_to "Back to user", user_path(@task.user) %></div>

app/views/tasks/index.html.erb
<%= stylesheet_link_tag 'style', 'tasks_index', medis: 'all', 'data-turbolinks-track': 'reload'%>

<div class="index_container">
  <h1>Tasks</h1>
  <div>
    <% @tasks.each do |task| %>
      <ul>
        <li><span class="dan">Content: <%= task.content %></li>
        <li><span class="dan2"><%= link_to "Edit", edit_task_path(task) %></li>
        <li><span class="dan2"><%= button_to "Delete", task_path(task), method: :delete, data: { confirm: "Are you sure you want to delete this task?" } %></li>
      </ul>
    <% end %>
  </div>

  <%= link_to "New task", new_task_path %>
  <%= link_to "Back to users", users_path %>
</div>

app/views/tasks/new.html.erb
<%= stylesheet_link_tag 'style', 'new_tasks', medis: 'all', 'data-turbolinks': 'reload' %>

<div class="new_tasks_contaner">
  <h1>New Task</h1>

  <%= form_with(model: @task) do |form| %>
    <div><%= form.label :user_name %></div>
    <div><%= form.text_field :user_name %></div>
    <div><%= form.label :content %></div>
    <div><%= form.text_area :content %></div>
    <div><%= form.submit %></div>
  <% end %>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'style', 'edit', media: 'all', 'data-turbolinks-track': 'reload' %>

<% content_for :title, "Edit User" %>

<div class="edit_container">
  <h2>ユーザー情報編集</h2>

  <%= form_for(@user, url: registration_path(@user), html: { method: :put }) do |f| %>
    <ul class="form_list">
      <li class="form_group">
        <div class="form_spacing">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
      </li>

      <li class="form_group">
        <div class="form_spacing">
          <%= f.label :email %>
          <%= f.email_field :email %>
        </div>
      </li>
    </ul>

    <ul class="form_list">
      <li class="form_group">
        <div class="form-spacing">
          <%= f.label :新しいパスワード %>
          <%= f.password_field :password, autocomplete: "off" %>
        </div>
      </li>

      <li class="form_group">
        <div class="form_spacing">
          <%= f.label :現在のパスワード %>
          <%= f.password_field :current_password, autocomplete: "off" %>
        </div>
      </li>
    </ul>

    <%= f.submit "Update" %>
  <% end %>

  <%= button_to "Delete Account", registration_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete your account?" } %>
  
  <!-- CSSクラスを使用して「ユーザー一覧に戻る」リンクをスタイリング -->
  <%= link_to "ユーザー一覧に戻る", users_path, class: "back-link" %>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'style', 'index', medis: 'all', 'data-turbolinks-track': 'reload' %>

<div class="index_container">
  <h1>Users</h1>

  <div>
    <% @users.each do |user| %>
      <% if current_user == user %>
        <div style="display: flex;">
          <div style="width: 160px;">User: <%= user.name %></div>
          <div><%= button_to "show", user_path(user), method: :get %></div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= link_to "New Users", new_user_path %>

  <% if user_signed_in? %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
  <% end %>
<div>

app/views/users/new.html.erb
<%= stylesheet_link_tag 'style', 'new', medis: 'all', 'data-turbolinks-track': 'reload' %>

<div class="new_continer">
  <h1>New User</h1>
  <%= form_with(model: @user) do |form| %>
    <ul>
      <li>
        <%= form.label :name %>
        <%= form.text_field :name %>
      </li>

      <li>
        <%= form.label :email %>
        <%= form.text_field :email %>
      </li>

      <li>
        <%= form.label :password %>
        <%= form.text_field :password %>
      </li>
    </ul>

      <li>
        <%= form.submit %>
      </li>
  <% end %>

    <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'style', 'show', medis: 'all', 'data-turbolinks-track': 'reload' %>

<div class="show_container">
  <h1>User</h1>

  <ul>
    <li>
      <strong>Name:</strong> <%= @user.name %>
    </li>
    <li>
      <strong>Email:</strong> <%= @user.email %>
    </li>
  </ul>

  <div>
    <%= link_to "Edit User", edit_user_path(@user) %>
    <%= button_to "Delete User", user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete this user?" } %>
  </div>
  
  <% if user_signed_in? %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
  <% end %>

  <%= link_to "Back to users", users_path %>
  <%= link_to "Task List", tasks_path %>
</div>